# Generated by Django 5.2.1 on 2025-09-30 21:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_participants_are_the_same_person'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='Participants are the same person',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.CheckConstraint(condition=models.Q(('participant1', models.F('participant2')), _negated=True), name='Participants are the same person'),
        ),
    ]
