# Generated by Django 5.2.1 on 2025-08-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='images/default_user_image.png', upload_to='images/'),
        ),
    ]
