# Generated by Django 5.2.1 on 2025-09-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='default_user_image.png', upload_to='images/'),
        ),
    ]
